[tool.pylint.MASTER]

ignore = ["notebooks"]

[tool.pylint.messages_control]

disable = [
    "missing-function-docstring",
    "missing-final-newline",
    "missing-class-docstring",
    "missing-module-docstring",
    "invalid-name",
    "redefined-outer-name",
    "too-many-locals",
    "too-many-arguments",
    "unused-argument",
    "unused-variable",
    "singleton-comparison",
    "missing-timeout",
    "not-context-manager",
    "duplicate-code",
    "import-error"
    ]


[tool.black]
line-length = 88
target-version = ['py39']
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
length_sort = true
